"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta
import os
import cloudinary
import environ
import os

BASE_DIR = Path(__file__).resolve().parent.parent   
# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Use variables
DB_NAME = env('dbname')
DB_USER =env('user')
DB_PASSWORD =env('password')
DB_HOST =env('host')
DB_PORT =env('port')
CLOUDINARY_NAME = env('CLOUDINARY_NAME')
CLOUDINARY_API_KEY = env('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = env('CLOUDINARY_API_SECRET')
DJANGO_SECRET_KEY = env('DJANGO_SECRET_KEY')
REDIS_PORT = env('REDIS_PORT')
REDIS_SERVER = env('REDIS_SERVER')


MAILTRAP_BACKEND = env('MAILTRAP_BACKEND')
MAILTRAP_HOST = env('MAILTRAP_HOST')
MAILTRAP_HOST_USER = env('MAILTRAP_HOST_USER')
MAILTRAP_HOST_PASSWORD = env('MAILTRAP_HOST_PASSWORD')
MAILTRAP_PORT = env('MAILTRAP_PORT')
MAILTRAP_USE_TLS = env('MAILTRAP_USE_TLS')
MAILTRAP_USE_SSL = env('MAILTRAP_USE_SSL')

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ['localhost', '127.0.0.1','meeshoclone-api.onrender.com']

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "core",
    "users",
    "products",
    "carts",
    "orders",
    "payments",
    "reviews",
    "rest_framework",
    "rest_framework_simplejwt",
    'rest_framework_simplejwt.token_blacklist',
    "django_filters",
    'cloudinary',
    'cloudinary_storage',
    'django_celery_results',
    'django_celery_beat',
    "corsheaders",

]

CELERY_WORKER=  env.bool('CELERY_WORKER', default=False)    
if not CELERY_WORKER:
    INSTALLED_APPS+=[
    'django_weasyprint',
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,  
        'USER': DB_USER,  
        'PASSWORD': DB_PASSWORD,  
        'HOST': DB_HOST, 
        'PORT': DB_PORT, 
        "OPTIONS": {"sslmode": "require"} 
    }
}


cloudinary.config(
    cloud_name= CLOUDINARY_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    
    SECURE= True,
)


STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# definition for where to store media (images/videos)
# For Django 4.2+:
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle',
    #     "core.throttles.BurstRateThrottle",
    #     "core.throttles.SustainedRateThrottle"
        
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '150/min',
    #     'user': '250/hour',
    #     'auth':'10/day', 
    #     "burst":"5/sec",
    #     "sustained":"1000/day"
    # }
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Celery Configs
CELERY_TIMEZONE="Asia/Kolkata"
CELERY_BROKER_URL = f"redis://{REDIS_SERVER}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_RESULT_EXTENDED = True


# Mailtrap configs (prod) -- sent to rroxx460 only
EMAIL_BACKEND = MAILTRAP_BACKEND   
EMAIL_HOST = MAILTRAP_HOST
EMAIL_HOST_USER = MAILTRAP_HOST_USER
EMAIL_HOST_PASSWORD = MAILTRAP_HOST_PASSWORD
EMAIL_PORT = MAILTRAP_PORT
EMAIL_USE_TLS = MAILTRAP_USE_TLS
EMAIL_USE_SSL = MAILTRAP_USE_SSL



# Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_SERVER}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Razorpay

RAZORPAY_API_KEY=env("RAZORPAY_API_KEY")
RAZORPAY_API_KEY_SECRET=env("RAZORPAY_API_KEY_SECRET")


RAZORPAY_KEY_ID=RAZORPAY_API_KEY
RAZORPAY_KEY_SECRET=RAZORPAY_API_KEY_SECRET
RAZORPAY_CALLBACK_URL = "http://127.0.0.1:8000/payment/verify/"
REDIRECT_URL="http://localhost:5173/order/history/"

# For checkingn error log purposess.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "ERROR",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}


# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True


# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True