"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import private
from datetime import timedelta
import os
import cloudinary

DB_NAME = private.dbname
DB_USER = private.user
DB_PASSWORD =  private.password
DB_HOST = private.host
DB_PORT = private.port
CLOUDINARY_NAME = private.CLOUDINARY_NAME
CLOUDINARY_API_KEY = private.CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET = private.CLOUDINARY_API_SECRET
DJANGO_SECRET_KEY = private.DJANGO_SECRET_KEY
REDIS_PORT = private.REDIS_PORT
REDIS_SERVER = private.REDIS_SERVER


MAILTRAP_BACKEND = private.MAILTRAP_BACKEND
MAILTRAP_HOST = private.MAILTRAP_HOST
MAILTRAP_HOST_USER = private.MAILTRAP_HOST_USER
MAILTRAP_HOST_PASSWORD = private.MAILTRAP_HOST_PASSWORD
MAILTRAP_PORT = private.MAILTRAP_PORT
MAILTRAP_USE_TLS = private.MAILTRAP_USE_TLS
MAILTRAP_USE_SSL = private.MAILTRAP_USE_SSL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "core",
    "users",
    "products",
    "carts",
    "orders",
    "payments",
    "reviews",
    "rest_framework",
    "rest_framework_simplejwt",
    'rest_framework_simplejwt.token_blacklist',
    "django_filters",
    'cloudinary',
    'cloudinary_storage',
    'django_celery_results',
    'django_celery_beat',

    #  pip install flower

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,  # Replace with your database name
        'USER': DB_USER,  # Replace with your database username
        'PASSWORD': DB_PASSWORD,  # Replace with your database password
        'HOST': DB_HOST,  # Or the IP address/hostname of your PostgreSQL server
        'PORT': DB_PORT,  # Default PostgreSQL port
    }
}


cloudinary.config(
    cloud_name= CLOUDINARY_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    # optional: set folder root or secure_url
    SECURE= True,
)


STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# definition for where to store media (images/videos)
# For Django 4.2+:
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=50),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Celery Configs
CELERY_TIMEZONE="Asia/Kolkata"
CELERY_BROKER_URL = f"redis://{REDIS_SERVER}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


CELERY_RESULT_EXTENDED = True


# Mailtrap configs (prod) -- sent to rroxx460 only
EMAIL_BACKEND = MAILTRAP_BACKEND   
EMAIL_HOST = MAILTRAP_HOST
EMAIL_HOST_USER = MAILTRAP_HOST_USER
EMAIL_HOST_PASSWORD = MAILTRAP_HOST_PASSWORD
EMAIL_PORT = MAILTRAP_PORT
EMAIL_USE_TLS = MAILTRAP_USE_TLS
EMAIL_USE_SSL = MAILTRAP_USE_SSL


# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True


# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True